<div id="createTournamentPhtml">
    <i id="returnArrow" class="far fa-arrow-alt-circle-left"></i>
    <form method="post" action="">
        <fieldset>
            <input type="text" placeholder="Tournament name">
        </fieldset>
        <fieldset>
            <input type="text" placeholder="date">
        </fieldset>
        <fieldset>
            <ul>
                <li>
                    <label for="forTeam">for teams</label>
                    <input type="radio" name="soloTeam" id="asTeam">
                </li>
                <li>
                    <label for="forSolo">for 1v1 (solo)</label>
                    <input type="radio" name="soloTeam" id="solo">
                </li>
        </fieldset>
            <li>
                <input type="text" placeholder="average skill">
            </li>
        </ul>
        <button type="submit">CONFIRM</button>
    </form>
    <button id="helpBut"><i class="far fa-question-circle"></i></button>
</div>