<div id="createTournamentPhtml">
    <i id="returnArrow" class="far fa-arrow-alt-circle-left"></i>
    <form method="POST" action="">
        <fieldset>
            <input type="text" placeholder="Tournament name">
        </fieldset>
        <fieldset id="date">
            <label for="startDate">Launch date</label>
            <input type="date" name="startDate" placeholder="day">
        </fieldset>
        <fieldset>
            <ul>
                <li>
                    <label for="forTeam">for teams</label>
                    <input type="radio" name="soloTeam" id="asTeam">
                </li>
                <li>
                    <label for="forSolo">for 1v1 (solo)</label>
                    <input type="radio" name="soloTeam" id="solo">
                </li>
            </ul>
        </fieldset>
        <fieldset>
            <h2>Max participants</h2>
            <ul id="maxParticipants">
                <li>
                    <label for="32">32</label>
                    <input type="radio" name="maxParticipants" id="large">
                </li>
                <li>
                    <label for="16">16</label>
                    <input type="radio" name="maxParticipants" id="medium">
                </li>
                <li>
                    <label for="8">8</label>
                    <input type="radio" name="maxParticipants" id="small">
                </li>
        </fieldset>
        <fieldset>
            <li>
                <input type="text" placeholder="average skill">
            </li>
        </fieldset>
        <button type="submit">CONFIRM</button>
    </form>
    <button id="helpBut"><i class="far fa-question-circle"></i></button>
</div>