<section id="homeNav">
    <?php if(isset($_GET['flash']) && $_GET['flash'] == 'signUp'): ?>
        <div id='flash'>Your account has been created successfully !</div>
    <?php endif; ?>
    <?php if(isset($_GET['flash']) && $_GET['flash'] == 'tournament'): ?>
        <div id='flash'>Your tournament has been created successfully !</div>
    <?php endif; ?>
    <?php if(isset($_GET['flash']) && $_GET['flash'] == 'team'): ?>
        <div id='flash'>Your team has been created successfully !</div>
    <?php endif; ?>
    <?php if(isset($_GET['flash']) && $_GET['flash'] == 'sendInvite'): ?>
        <div id='flash'>Your invitation has been sent successfully !</div>
    <?php endif; ?>
    <?php if (isset($_GET['flash']) && $_GET['flash'] == 'notConnected'): ?>
        <div id='redFlash'>You have to be connected to acces to this functionality</div>
    <?php endif; ?>
    <?php if (isset($_GET['flash']) && $_GET['flash'] == 'incorrectForm'): ?>
        <div id='redFlash'>Incorrect informations in form</div>
    <?php endif; ?>
    <?php if(isset($_GET['flash']) && $_GET['flash'] == 'noPlayerFound'): ?>
        <div id='redFlash'>User does not exist</div>
    <?php endif; ?>
    <?php if (isset($_GET['flash']) && $_GET['flash'] == 'wrongUser'): ?>
        <div id='redFlash'>Unknown user</div>
    <?php endif; ?>
    <?php if (isset($_GET['flash']) && $_GET['flash'] == 'wrongTeam'): ?>
        <div id='redFlash'>Unknown team</div>
    <?php endif; ?>
    <div id="homeContentNav">
        <div class="homeContentDiv">
            <article>
                <i class="fas fa-hammer"></i>
                <p>Creat a tournament on the game of your choice</p>
                <button value="create">Create</button>
            </article>
            <article>
                <i class="fas fa-eye"></i>
                <p>Take a look among all referenced tournaments</p>
                <button value="find">Find</button>
            </article>
        </div>
        <div class="homeContentDiv">
            <article>
                <i class="fas fa-users"></i>
                <p>Research players for your team or a team to play with</p>
                <button value="team">Team</button>
            </article>
            <article>
                <i class="fas fa-home"></i>
                <p>Research a family for your team or teams for your family</p>
                <button id="famBut" value="family">Family</button>
            </article>
        </div>
        <div><button id="helpBut"><i class="far fa-question-circle"></i></button></div>
    </div>
</section>
<section id="homeExplain">
    <div>
        <article>
            <i class="fas fa-hammer"></i>
            <p>Allow you to create a tournament on the game of your choice with multiple filters to set the competition you really want. You can chose a specific skill rank, number of participants, a cashprice and more.</p>
        </article>
        <article>
            <i class="fas fa-eye"></i>
            <p>Navigate through all tournaments in a game category, you can also sort your research by filters like minimum skill require, date and more.</p>
        </article>
        <article>
            <i class="fas fa-users"></i>
            <p>This section permit you to create a team on the game you choosed, recruit players for your team or apply to one more team with your profil.</p>
        </article>
        <article>
            <i class="fas fa-home"></i>
            <p>As teams are for players, family are a group of teams. This section allow you to create a family, recruit teams for your family or apply one of your team in a family.</p>
        </article>
    </div>
    <div id="upButDiv"><button id="upBut"><i class="far fa-arrow-alt-circle-up"></i></button></div>
</section>
<script type="text/javascript" src="js/homeProgram.js"></script>
<link rel="stylesheet" href="css/homeNav.css">