<div id="homePhtml">
    <div id="homeNav">
        <div>
            <div>
                <i class="fas fa-hammer"></i>
                <p>Creat a tournament on the game of your choice</p>
                <button value="creat">Create</button>
            </div>
            <div>
                <i class="fas fa-eye"></i>
                <p>Take a look among all referenced tournaments</p>
                <button value="find">Find</button>
            </div>
        </div>
        <div>
            <div>
                <i class="fas fa-users"></i>
                <p>Research players for your team or a team to play with</p>
                <button value="team">Team</button>
            </div>
            <div>
                <i class="fas fa-home"></i>
                <p>Research a family for your team or teams for your family</p>
                <button value="team">Family</button>
            </div>
        </div>
    </div>
    <div id="homeExplain">
        <div class="homeExplainDiv">
            <img src="img/ladderExplain.jpg" alt="exemple de ladder"/>
        <div>
            <p>Ready Arena possède un systeme interne de classement 
            des joueurs, des équipes et des familles. A la fin de chaque tournois chaque joueur se vois attribué un certain
            montant de point en fonction de sa position finale dans l'arbre de classement, qui vient s'ajouter a son total de point.</p>
            <p>Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! </p>
        </div>
    </div>
    <div class="homeExplainDiv">
        <img src="img/ladderExplain.jpg" alt="exemple de ladder"/>
        <div>
            <p>Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! </p>
            <p>Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! </p>
        </div>
    </div>
</div>