<div id="homePhtml">
    <div id="homeNav">
        <div>
            <div>
                <i class="fas fa-hammer"></i>
                <p>Creat a tournament on the game of your choice</p>
                <button value="creat">Create</button>
            </div>
            <div>
                <i class="fas fa-eye"></i>
                <p>Take a look among all referenced tournaments</p>
                <button value="find">Find</button>
            </div>
        </div>
        <div>
            <div>
                <i class="fas fa-users"></i>
                <p>Research players for your team or a team to play with</p>
                <button value="team">Team</button>
            </div>
            <div>
                <i class="fas fa-home"></i>
                <p>Research a family for your team or teams for your family</p>
                <button value="team">Family</button>
            </div>
        </div>
    </div>
    <div id="homeExplain">
        <div>
            <article>
                <i class="fas fa-hammer"></i>
                <p>Allow you to create a tournament on the game of your choice with multiple filters to set the competition you really want. You can chose a specific skill rank, number of participants, a cashprice and more.</p>
            </article>
            <article>
                <i class="fas fa-eye"></i>
                <p>Navigate through all tournaments in a game categorie, you can also sort your research by filters like minimum skill require, date and more.</p>
            </article>
            <article>
                <i class="fas fa-users"></i>
                <p>This section permit you to create a team on the game you choosed, recruit players for your team or apply to one more team with your profil.</p>
            </article>
            <article>
                <i class="fas fa-home"></i>
                <p>As teams are for players, family are a group of teams. This section allow you to create a family, recruit teams for your family and apply one of your team in a family.</p>
            </article>
        </div>
    </div>
</div>