<div id="supportPhtml">
    <h1>Who's behind all of this ?</h1>
    <article>
        <p>Freshly out from a three month web formation dispense by the 3W Academy i have been on this project since early February 2020 only by myself to validate my diploma.</p>
        <p> ReadyArena's goal is to permit its users to find, create and participate to non official tournaments on the games of their choice, also find and create teams. I wanted to had a family functionnality witch can federate some teams under a same flag. On an other hand ReadyArena allow its users to rank themself into an internal ladder as individual competitors.</p>
    </article>
</div>