<div id="findTurnamentPhmtl">
    <p>Select a game</p>
    <div>
        <div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
        </div>
        <div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
        </div>
        <div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
        </div>
    </div>
</div>