<div id="indexPhtml">
    <div id="indexPDiv">
        <div>
            <div>
                <i class="fas fa-hammer"></i>
                <p>Creat a tournament on the game of your choice</p>
                <button value="creat">Create</button>
            </div>
            <div>
                <i class="fas fa-eye"></i>
                <p>Take a look among all referenced tournaments</p>
                <button value="find">Find</button>
            </div>
        </div>
        <div>
            <div>
                <i class="fas fa-users"></i>
                <p>Research players for your team or a team to play with</p>
                <button value="team">Team</button>
            </div>
            <div>
                <i class="fas fa-home"></i>
                <p>Research a family for your team or teams for your family</p>
                <button value="team">Family</button>
            </div>
        </div>
    </div>
</div>