<div id="oneTeamPhtml">
    <div>
        <h1><?= $team[0]['name'] ?></h1>
        <img src='<?= '../' ?>img\games_icone\<?= $game[0]['icone'] ?>'/>
    </div>
    <div id="mainContent">
        <div><p><?= $team[0]['comment'] ?></p></div>
        <div>
            <button value="apply">APPLY</button>
            <div><h2>Captain : <?= $team[0]['captain'] ?></h2></div>
            <div><<h2>Teammates</span></h2></div>
            <ul>
                <?php foreach($players as $player): ?>
                    <a href="onePlayer.php?path=onePlayer&id=<?= $player[0]['id'] ?>"><li><div>#<?= $player[0]['rank'] ?></div> <div><?= $player[0]['name'] ?></div></li></a>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>