<div id="oneTeamPhtml">
    <div>
        <h1><?= $team[0]['name'] ?></h1>
        <img src='<?= '../' ?>img\games_icone\<?= $game[0]['icone'] ?>'/>
    </div>
    <div id="mainContent">
        <div id="commentDiv">
            <p><?= $team[0]['comment'] ?></p>
            <?php if (isset($_SESSION['name']) && $_SESSION['name'] == $team[0]['captain']): ?>
                <form action="oneTeam.php?path=oneTeam&id=<?= $team[0]['id'] ?>&game=<?= $team[0]['game'] ?>&reloadComment" method="post">
                    <input type="text" name="reloadComment" placeholder="new comment">
                </form>
            <?php endif; ?>
        </div>
        <div>
            <h2>Users waiting for validation</h2>
            <ul>
                <?php foreach($waitingPlayers as $waitingPlayer): ?>
                    <div class="waitingPlayer">
                        <a href="onePlayer.php?path=onePlayer&id=<?= $waitingPlayer[0]['id'] ?>"><li><?= $waitingPlayer[0]['name'] ?></li></a>
                        <?php if (isset($_SESSION['name']) && $alreadyRegister === true): ?>
                            <a href="oneTeamWaitingList.php?user=<?= $waitingPlayer[0]['id'] ?>&team=<?= $team[0]['id'] ?>&choice=yes"><i class="far fa-check-circle"></i></a>
                            <a href="oneTeamWaitingList.php?user=<?= $waitingPlayer[0]['id'] ?>&team=<?= $team[0]['id'] ?>&choice=no"><i class="far fa-times-circle"></i></a>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </ul>
        </div>
        <div>
            <h2>Upcoming Tournaments</h2>
            <?php foreach($upcomingTournaments as $oneTournament): ?>
                <a href="oneTournament.php?path=oneTournament&id=<?= $oneTournament[0]['id'] ?>&game=<?= $oneTournament[0]['game'] ?>&format=<?= $oneTournament[0]['format'] ?>"><div class='UpTournament'><?= $oneTournament[0]['name'] ?></br><?= $oneTournament[0]['game'] ?></div></a>
            <?php endforeach; ?>
        </div>
        <div>
            <?php if ($alreadyIn !== true && isset($_SESSION['name'])): ?>
                <form action="applyTeam.php?id=<?= $_GET['id'] ?>" method="post">
                    <button value="apply">APPLY</button>
                </form>
            <?php endif; ?>
            <div><h2>Captain : <?= $team[0]['captain'] ?></h2></div>
            <div><<h2>Teammates</span></h2></div>
            <ul>
                <?php foreach($players as $player): ?>
                    <?php if (isset($_SESSION['name']) && $_SESSION['name'] === $team[0]['captain']): ?>
                        <div class="adminTeammatesDiv">
                    <?php endif; ?>
                    <a href="onePlayer.php?path=onePlayer&id=<?= $player[0]['id'] ?>"><li><div>#<?= $player[0]['rank'] ?></div> <div><?= $player[0]['name'] ?></div></li></a>
                    <?php if (isset($_SESSION['name']) && $_SESSION['name'] === $team[0]['captain']): ?>
                        <a href="oneTeam.php?path=oneTeam&id=<?= $team[0]['id'] ?>&game=<?= $team[0]['game'] ?>&user=<?= $player[0]['id'] ?>&deletePlayer"><i class="far fa-times-circle"></i></a>
                    <?php endif; ?>
                    <?php if (isset($_SESSION['name']) && $_SESSION['name'] === $team[0]['captain']): ?>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>