<!DOCTYPE html>
<html>
    <head>
        <title>Ready Arena</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Candal|Dosis|Open+Sans">
        <script src="https://kit.fontawesome.com/f6ab443034.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="/finalProject/css/style.css" type="text/css" />
        <link rel="stylesheet" href="/finalProject/css/<?= $_GET['path'] ?>.css" type="text/css" />
        <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>
        <script src="https://kit.fontawesome.com/f6ab443034.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <header>
            <a href="/finalProject/index.php"><img src="/finalProject/img/logo_ReadyArena.png" /></a>
            <div>
                <i class="fas fa-search"></i>
                <form>
                    <input type="text">
                </form>
            </div>
                <?php if($connect == true): ?>
                <div>
                    <a href="/finalProject/controllers/LoginController.php?path=Login" id="login">Login</a>
                    <a href="/finalProject/controllers/SignUpController.php?path=SignUp" id="signUp">Sign up</a>
                </div>
                <?php endif; ?>
                <?php if($connect == false): ?>
                <div id='divIconeProfil'><a href="#" id="iconeProfil"><div id="profilIcone"></div></a></div>
                <?php endif; ?>
        </header>
        <main>
            <button id="arrowMenu">MENU</button>
            <aside>
                <nav class="hideAside">
                    <ul>
                        <?php if($_GET['path'] !== 'home'): ?>
                            <?php if($_GET['path'] !== 'MyTounaments'): ?>
                            <a href="MyTournamentsController.php"><li>My tournaments</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'MyTeams'): ?>
                            <a href="MyTeamsController.php"><li>My teams</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'MyFamily'): ?>
                            <a href="MyFamilyController.php"><li>My Family</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'FriendList'): ?>
                            <a href="FriendListController.php"><li>Friend list</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'Ladder'): ?>
                            <a href="LadderController.php?path=Ladder"><li>Ladder</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'support'): ?>
                            <a href="SupportController.php?path=support"><li>Support</li></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if($_GET['path'] == 'home'): ?>
                            <?php if($_GET['path'] !== 'MyTournaments'): ?>
                            <a href="controllers/MyTournamentsController.php"><li>My tournaments</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'MyTeams'): ?>
                            <a href="controllers/MyTeamsController.php"><li>My teams</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'MyFamily'): ?>
                            <a href="controllers/MyFamilyController.php"><li>My Family</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'FriendList'): ?>
                            <a href="controllers/FriendListController.php"><li>Friend list</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'Ladder'): ?>
                            <a href="controllers/LadderController.php?path=Ladder"><li>Ladder</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'support'): ?>
                            <a href="controllers/SupportController.php?path=support"><li>Support</li></a>
                            <?php endif; ?>
                        <?php endif; ?>
                    </ul>
                </nav>
            </aside>
            <?php include $dataview; ?>
        </main>
        <script type="text/javascript" src="/finalProject/js/main.js"></script>
        <script type="text/javascript" src="/finalProject/js/ajax.js"></script>
    </body>
</html>