<!DOCTYPE html>
<html>
    <head>
        <title>Ready Arena</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Candal|Dosis|Open+Sans">
        <script src="https://kit.fontawesome.com/f6ab443034.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="/finalProject/css/style.css" type="text/css" />
        <link rel="stylesheet" href="/finalProject/css/<?= $_GET['path'] ?>.css" type="text/css" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>
        <script src="https://kit.fontawesome.com/f6ab443034.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
        <script type="module" src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.mjs"></script>
    </head>
    <body>
        <header>
            <a href="/finalProject/index.php"><img src="/finalProject/img/logo_ReadyArena.png" /></a>
            <?php if (!isset($_SESSION['name'])): ?>
                <div id="searchBar">
                    <i class="fas fa-search"></i>
                    <?php if ($_GET['path'] == 'home'): ?>
                        <form method="get" action="controllers/findPlayerBar.php">
                            <input type="text" placeholder="find a player" name="findPlayer">
                        </form>
                    <?php endif; ?>
                    <?php if ($_GET['path'] !== 'home'): ?>
                        <form method="get" action="../controllers/findPlayerBar.php">
                            <input type="text" placeholder="find a player" name="findPlayer">
                        </form>
                    <?php endif; ?> 
                </div>
            <?php endif; ?>
            <?php if (isset($_SESSION['name'])): ?>
                <div id="searchBar" class="connectedSearchBar">
                    <i class="fas fa-search"></i>
                    <?php if ($_GET['path'] == 'home'): ?>
                        <form method="get" action="controllers/findPlayerBar.php">
                            <input type="text" placeholder="find a player" name="findPlayer">
                        </form>
                    <?php endif; ?>
                    <?php if ($_GET['path'] !== 'home'): ?>
                        <form method="get" action="../controllers/findPlayerBar.php">
                            <input type="text" placeholder="find a player" name="findPlayer">
                        </form>
                    <?php endif; ?> 
                </div>
            <?php endif; ?>
                <?php if(!isset($_SESSION['name'])): ?>
                <div id='connectDiv'>
                    <a href="/finalProject/controllers/LoginController.php?path=Login" id="login">Login</a>
                    <a href="/finalProject/controllers/SignUpController.php?path=SignUp" id="signUp">Sign up</a>
                </div>
                <?php endif; ?>
                <?php if(isset($_SESSION['name'])): ?>
                <div id='divIconeProfil'>
                    <?php if ($_GET['path'] == 'home'): ?>
                        <a href="controllers/onePlayer.php?path=onePlayer&id=<?=$_SESSION['id']?>" id="headerProfil"><h4><?= $_SESSION['name'] ?></h4></a>
                        <a href="controllers/LoginController.php?action=disconnect" id="disconnect">Disconnect</a>
                    <?php endif; ?>
                    <?php if ($_GET['path'] !== 'home'): ?>
                        <a href="onePlayer.php?path=onePlayer&id=<?=$_SESSION['id']?>" id="headerProfil"><h4><?= $_SESSION['name'] ?></h4></a>
                        <a href="LoginController.php?action=disconnect" id="disconnect">Disconnect</a>
                    <?php endif; ?>
                </div>
                <?php endif; ?>
        </header>
        <main>
            <button id="arrowMenu">MENU</button>
            <aside>
                <nav class="hideAside">
                    <ul>
                        <?php if($_GET['path'] !== 'home'): ?>
                            <a href="../index.php"><li>Home</li></a>
                            <?php if($_GET['path'] !== 'onePlayer' && isset($_SESSION['id'])): ?>
                            <a href="onePlayer.php?path=onePlayer&id=<?= $_SESSION['id'] ?>"><li>My profil</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'Ladder'): ?>
                            <a href="LadderController.php?path=Ladder&order=rank"><li>Ladder</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'support'): ?>
                            <a href="SupportController.php?path=support"><li>Support</li></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if($_GET['path'] == 'home'): ?>
                            <?php if($_GET['path'] !== 'onePlayer' && isset($_SESSION['id'])): ?>
                            <a href="controllers/onePlayer.php?path=onePlayer&id=<?= $_SESSION['id'] ?>"><li>My profil</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'Ladder'): ?>
                            <a href="controllers/LadderController.php?path=Ladder&order=rank"><li>Ladder</li></a>
                            <?php endif; ?>
                            <?php if($_GET['path'] !== 'support'): ?>
                            <a href="controllers/SupportController.php?path=support"><li>Support</li></a>
                            <?php endif; ?>
                        <?php endif; ?>
                    </ul>
                </nav>
            </aside>
            <?php include $dataview; ?>
        </main>
        <div id='hidden'></div>
        <script type="text/javascript" src="/finalProject/js/main.js"></script>
        <script type="text/javascript" src="/finalProject/js/ajax.js"></script>
    </body>
</html>