<!DOCTYPE html>
<html>
    <head>
        <title>Ready Arena</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Candal|Dosis|Open+Sans">
        <script src="https://kit.fontawesome.com/f6ab443034.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="/finalProject/css/style.css" type="text/css" />
        <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>
        <script src="https://kit.fontawesome.com/f6ab443034.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <header>
            <a href="/finalProject/index.php"><img src="/finalProject/img/logo_ReadyArena.png" /></a>
            <div>
                <i class="fas fa-search"></i>
                <form>
                    <input type="text">
                </form>
            </div>
            <div>
                <a href="#" id="login">Login</a>
                <a href="#" id="signUp">Sign up</a>
                <!--<a href="#"><div id="profilIcone"></div></a>-->
            </div>
        </header>
        <main>
            <button id="arrowMenu">MENU</button>
            <aside>
                <nav class="hideAside">
                    <ul>
                        <?php if($_GET['path'] !== 'MyTounaments') : ?>
                        <a href="controllers/MyTournamentsController/MyTournamentsController.php"><li>My tournaments</li></a>
                        <?php endif; ?>
                        <?php if($_GET['path'] !== 'MyTeams') : ?>
                        <a href="controller/MyTeamsController/MyTeamsController.php"><li>My teams</li></a>
                        <?php endif; ?>
                        <?php if($_GET['path'] !== 'MyFamily') : ?>
                        <a href="controllers/MyFamilyController/MyFamilyController.php"><li>My Family</li></a>
                        <?php endif; ?>
                        <?php if($_GET['path'] !== 'FriendList') : ?>
                        <a href="controllers/FriendListController/FriendListController.php"><li>Friend list</li></a>
                        <?php endif; ?>
                        <?php if($_GET['path'] !== 'Ladder') : ?>
                        <a href="contorllers/LadderController/LadderController.php"><li>Ladder</li></a>
                        <?php endif; ?>
                        <?php if($_GET['path'] !== 'support') : ?>
                        <a href="controllers/SupportController/SupportController.php?path=support"><li>Support</li></a>
                        <?php endif; ?>
                    </ul>
                </nav>
            </aside>
            <?php include $dataview; ?>
        </main>
        <script type="text/javascript" src="/finalProject/js/main.js"></script>
        <script type="text/javascript" src="/finalProject/js/ajax.js"></script>
    </body>
</html>