<div id="allGamesPhtml">
    <div id="top">
        <i id="returnArrow" class="far fa-arrow-alt-circle-left"></i>
        <p>Select a game</p>
    </div>
    <div id="bottom">
        <div>
            <?php foreach ($games as $game) : ?>
                
            <?php endforeach; ?>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
        </div>
        <div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
        </div>
        <div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
            <div class="gameIcone"></div>
        </div>
    </div>
</div>