<div id="allGamesPhtml">
    <div id="top">
        <i id="returnArrow" class="far fa-arrow-alt-circle-left"></i>
        <p>Select a game</p>
    </div>
    <div id="bottom">
        <div>
            <?php foreach ($allGames as $game) : ?>
                <button class="gameIcone" style="background-image: url('img/games_icone/<?= $game['icone'] ?>')"></button>
            <?php endforeach; ?>
            
            <?php
                var_dump($game[0]['icone']);
            ?>
        </div>
    </div>
</div>