<div id="allGamesPhtml">
    <div id="top">
        <i id="returnArrow" class="far fa-arrow-alt-circle-left"></i>
        <p>Select a game</p>
    </div>
    <div id="bottom">
        <div id="container">
            <button  value="dota2" class="gameIcone" style="background-image: url('img/games_icone/Dota2.png'); background-size: 81px; background-color:black;">
            <button  value="CS:GO" class="gameIcone" style="background-image: url('img/games_icone/csgo.jpg')">
            <button  value="LeagueOfLegends" class="gameIcone" style="background-image: url('img/games_icone/leagueIcone.png'); background-size: 90px; background-color:black;">
            <button  value="Overwatch" class="gameIcone" style="background-image: url('img/games_icone/overwatch.png')">
            <button  value="rocketLeague" class="gameIcone" style="background-image: url('img/games_icone/rocketLeague.png'); background-size: 100px; background-color:black">
            <button  value="SSBU" class="gameIcone" style="background-image: url('img/games_icone/smash.png'); background-size: 90px; background-color:black;">
            <button  value="Hearthstone" class="gameIcone" style="background-image: url('img/games_icone/hearthStone.png'); background-color:black;">
            <button  value="Starcraft2" class="gameIcone" style="background-image: url('img/games_icone/Starcraft2.png'); background-color:black; background-size: 90px;">
            <button  value="WorldOfWarcraft" class="gameIcone" style="background-image: url('img/games_icone/WorldOfWarcraft.png'); background-color:black; background-size: 90px;">
            <button  value="Fifa2020" class="gameIcone" style="background-image: url('img/games_icone/fifa2020.png'); background-size: 90px; background-color:black">
            <button  value="Osu" class="gameIcone" style="background-image: url('img/games_icone/osu.png'); background-color:black; background-size: 90px;">
            <button  value="Warcraft3-reforged" class="gameIcone" style="background-image: url('img/games_icone/war3.png'); background-size: 100px; background-color:black">
        </div>
    </div>
</div>
<link rel="stylesheet" href="/finalProject/css/allGames.css">