<div id='signupPhtml'>
    <form action="addUser.php" method="post">
        <ul>
            <li>
                <input type="text" placeholder="name" name="name">
            </li>
            <li>
                <input type="text" placeholder="email" name="email">
            </li>
            <li>
                <input type="text" placeholder="password" name="password">
            </li>
            <li>
                <input type="text" placeholder="confirm password" name="confirmPWD">
            </li>
        </ul>
        <button type="submit">CONFIRM</button>
    </form>
</div>