<div id='signupPhtml'>
    <?php if (isset($_GET['error'])): ?>
        <?php if ($_GET['error'] == 'empty'): ?>
            <h1>EMPTY FIELD</h1>
        <?php endif; ?>
        <?php if ($_GET['error'] == 'name'): ?>
            <h1>INCORRECT NAME FIELD</h1>
        <?php endif; ?>
        <?php if ($_GET['error'] == 'email'): ?>
            <h1>INCORRECT EMAIL FIELD</h1>
        <?php endif; ?>
        <?php if ($_GET['error'] == 'PWD'): ?>
            <h1>INCORRECT PASSWORD FIELD</h1>
        <?php endif; ?>
        <?php if ($_GET['error'] == 'confirmPWD'): ?>
            <h1>INCORRECT CONFIRM PASSWORD FIELD</h1>
        <?php endif; ?>
    <?php endif; ?>
    <form action="addUser.php" method="post">
        <ul>
            <li>
                <input type="text" placeholder="name" name="name">
            </li>
            <li>
                <input type="text" placeholder="email" name="email">
            </li>
            <li>
                <input type="text" placeholder="password" name="password">
            </li>
            <li>
                <input type="text" placeholder="confirm password" name="confirmPWD">
            </li>
        </ul>
        <button type="submit">CONFIRM</button>
    </form>
</div>