<div id='signupPhtml'>
    <form>
        <ul>
            <li>
                <input type="text" placeholder="name">
            </li>
            <li>
                <input type="text" placeholder="email">
            </li>
            <li>
                <input type="text" placeholder="password">
            </li>
            <li>
                <input type="text" placeholder="confirm password">
            </li>
        </ul>
    </form>
    <button>CONFIRM</button>
</div>