<article id="createExplain">
    <p><span>1</span> - Chose a name for your tournament</p>
    <p><span>2</span> - Then set the lauch date</p>
    <p><span>3</span> - Chose between a tournament design for players or teams</p>
    <p><span>4</span> - Finally set how many players or teams will be allow to participate (this also mean the number of rounds)</p>
    <p><span>5</span> (optional) you can had a comment for everyone to see on the tournament page</p>
    <div id="upButDiv"><button id="upBut"><i class="far fa-arrow-alt-circle-up"></i></button></div>
</article>