<div id="ladderPhtml">
    <div id="ladderExplain">
        <div class="ladderExplainDiv">
            <img src="img/ladderExplain.jpg" alt="exemple de ladder"/>
            <div>
                <p>Ready Arena possède un systeme interne de classement 
                des joueurs, des équipes et des familles. A la fin de chaque tournois chaque joueur se vois attribué un certain
                montant de point en fonction de sa position finale dans l'arbre de classement, qui vient s'ajouter a son total de point.</p>
                <p>Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! </p>
            </div>
        </div>
    </div>
        <div class="ladderExplainDiv">
            <img src="img/ladderExplain.jpg" alt="exemple de ladder"/>
            <div>
                <p>Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! </p>
                <p>Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! Ladder explained ! </p>
            </div>
        </div>
    </div>
</div>