<div id="createTeam">
    <form action="" method="post">
        <fieldset>
            <input type="text" placeholder="Team name" name="name">
        </fieldset>
        <fieldset>
            <h2>Is your team looking for people ?</h2>
            <div>
                <label for="yes">Yes</label>
                <input type="radio" name="LFP" value="yes" class="LFP">
                <label for="no">No</label>
                <input type="radio" name="LFP" value="no" class="LFP">
            </div>
        </fieldset>
        <fieldset>
            <input type="text" name="comment" placeholder="comment" id="comment">
        </fieldset>
        <button type="submit">CONFIRM</button>
    </form>
</div>