<div id='loginPhtml'>
    <?php if(isset($_GET['flashError'])): ?>
        <p><span>INCORRECT INFORMATIONS<span></p>
    <?php endif; ?>
    <form method="post" action="./tryLogin.php">
        <input type="text" placeholder="email" name="Email">
        <input type="password" placeholder="password" name="Password">
        <div>
            <button type="submit" name="Submit" value="confirm" id="loginButton">CONFIRM</button>
        </div>
    </form>
</div>