<div id="functionTeamPhtml">
    <i id="returnArrow" class="far fa-arrow-alt-circle-left"></i>
    <nav>
        <a href="./controllers/createTeam.php?path=createTeam"><button>Create a team</button></a>
        <a href="./controllers/findATeam.php?path=findATeam"><button>Find a team</button></a>
        <a href="./controllers/findTeammates.php?path=findTeammates"><button>Find teammates</button></a>
    </nav>
</div>