    <div class="homeContentDiv">
        <article>
            <i class="fas fa-hammer"></i>
            <p>Creat a tournament on the game of your choice</p>
            <button value="create">Create</button>
        </article>
        <article>
            <i class="fas fa-eye"></i>
            <p>Take a look among all referenced tournaments</p>
            <button value="find">Find</button>
        </article>
    </div>
    <div class="homeContentDiv">
        <article>
            <i class="fas fa-users"></i>
            <p>Research players for your team or a team to play with</p>
            <button value="team">Team</button>
        </article>
        <article>
            <i class="fas fa-home"></i>
            <p>Research a family for your team or teams for your family</p>
            <button value="family">Family</button>
        </article>
    </div>
</section>