<div id='onePlayerPhtml'>
    <h1><?= $user[0]['name'] ?></h1>
    <h2>#<?= $user[0]['rank'] ?></h2>

    <div>
        <div id="seekTeam">
            <h3>Looking for a team on</h3>
            <?php foreach($games as $game): ?>
                <img src="../img/games_icone/<?= $game[0]['icone'] ?>" alt="<?= $game[0]['name'] ?> icone">
            <?php endforeach; ?>
        </div>
        <div id='upTourn'>
            <h3>Upcoming Tournaments</h3>
            <?php foreach($tournaments as $tournament): ?>
                <a href="oneTournament.php?path=oneTournament&id=<?= $tournament[0]['id'] ?>&game=<?= $tournament[0]['game'] ?>"><div class='UpTournament'><?= $tournament[0]['name'] ?></br><?= $tournament[0]['game'] ?></div></a>
            <?php endforeach; ?>
        </div>
        <div id='teams'>
            <?php if (isset($_SESSION['id']) && $_SESSION['id'] !== $_GET['id']): ?>
            <form action="inviteToTeam.php?path=inviteToTeam&id=<?= $_GET['id'] ?>" method="post">
                <button>Send invitation</button>
            </form>
            <?php endif; ?>
            <h3><?= $user[0]['name'] ?>'s teams</h3>
            <?php foreach($teams as $team): ?>
                <a href="oneTeam.php?path=oneTeam&id=<?= $team[0]['id'] ?>&game=<?= $team[0]['game'] ?>"><div class='team'><?= $team[0]['name'] ?></br><?= $team[0]['game'] ?></div></a>
            <?php endforeach; ?>
        </div>
    </div>
</div>