<div id='onePlayerPhtml'>
    <h1><?= $user[0]['name'] ?></h1>
    <h2>#<?= $user[0]['rank'] ?></h2>

    <div>
        <div id="seekTeam">
            <h3>Looking for a team on</h3>
            <?php foreach($games as $game): ?>
                <img src="../img/games_icone/<?= $game[0]['icone'] ?>" alt="<?= $game[0]['name'] ?> icone">
                <?php if (isset($_SESSION['id']) && $_SESSION['id'] === $_GET['id']): ?>
                    <a href="onePlayerAdmin.php?user=<?= $_GET['id'] ?>&game=<?= $game[0]['id'] ?>&choice=LFT"><i class="far fa-times-circle"></i></a>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if (isset($_SESSION['name'])): ?>
                <?php if ($_SESSION['name'] == $user[0]['name']): ?>
                    <?php if (isset($invite_list)): ?>
                        <h3>Teams invitations</h3>
                        <?php for($i = 0;$i < count($invite_list);$i++): ?>
                            <div class="inviteTeam">
                                <a href="oneTeam.php?path=oneTeam&id=<?= $invite_list[$i][0]['id'] ?>&game=<?= $invite_list[$i][0]['game'] ?>" class="team"><?= $invite_list[$i][0]['name'] ?></a>
                                <a href="onePlayerInvitations.php?user=<?= $user[0]['id'] ?>&team=<?= $invite_list[$i][0]['id'] ?>&choice=yes"><i class="far fa-check-circle"></i></a>
                                <a href="onePlayerInvitations.php?user=<?= $user[0]['id'] ?>&team=<?= $invite_list[$i][0]['id'] ?>&choice=no"><i class="far fa-times-circle"></i></a>
                            </div>
                        <?php endfor; ?>
                    <?php endif; ?>
                <?php endif;?>
            <?php endif; ?>
        </div>
        <div id='upTourn'>
            <h3>Upcoming Tournaments</h3>
            <?php foreach($tournaments as $tournament): ?>
                <a href="oneTournament.php?path=oneTournament&id=<?= $tournament[0]['id'] ?>&game=<?= $tournament[0]['game'] ?>"><div class='UpTournament'><?= $tournament[0]['name'] ?></br><?= $tournament[0]['game'] ?></div></a>
            <?php endforeach; ?>
        </div>
        <div id='teams'>
            <?php if (isset($_SESSION['id']) && $_SESSION['id'] !== $_GET['id']): ?>
                <form action="inviteToTeam.php?path=inviteToTeam&id=<?= $_GET['id'] ?>" method="post">
                    <button>Send invitation</button>
                </form>
            <?php endif; ?>
            <h3><?= $user[0]['name'] ?>'s teams</h3>
            <?php foreach($teams as $team): ?>
                <div class="myTeam">
                    <a href="oneTeam.php?path=oneTeam&id=<?= $team[0]['id'] ?>&game=<?= $team[0]['game'] ?>"><div class='team'><?= $team[0]['name'] ?></br><?= $team[0]['game'] ?></div></a>
                    <?php if (isset($_SESSION['id']) && $_SESSION['id'] === $_GET['id']): ?>
                        <a href="onePlayerAdmin.php?user=<?= $_GET['id'] ?>&team=<?= $team[0]['id'] ?>&choice=team"><i class="far fa-times-circle"></i></a>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>